INSERT INTO public.location (number, street) VALUES ('23,', 'Vladimir Polezhanovski Rd');
INSERT INTO public.restaurant (average_rating, delivery_time, logo, name, photo, location_id) VALUES (0, '30-40 min', 'assets/images/fat_kitchen_bistro.png', 'Fat Kitchen Bistro', 'https://korpa.ba/restaurant_uploads/iHmxz2XLPsKADTnKMg3VJYNIFml6AVhe.jpg', (select max(id) from public.location));
INSERT INTO public.users (email, name, password, phone, surname, username, role) VALUES ('fat_kitchen_bistro_employee@mail.com', 'Employee', '$2a$10$VAlO0DtwWX42GHzGGM0DHOIx2kLX1EAhLwaTrXwEsj5n5K9Lr7EQO', '071234567', 'Fat Kitchen Bistro', 'fat_kitchen_bistro_employee', 'employee');
INSERT INTO public.restaurant_employee (user_id, restaurant_id) VALUES ((select max(user_id) from public.users), (select max(id) from public.restaurant));
insert into public.category (name, photo) VALUES ('Sandwiches', '/') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.food (name, photo, price, restaurant_id) VALUES ('Fat Pork', 'https://korpa.ba/product_uploads/18oemSNLtMAnV4LzIbRlkynTAf9iqaKs.jpg', 270, (select max(id) from public.restaurant where name = 'Fat Kitchen Bistro'));
INSERT INTO public.category_of_food (food_id, category_id) VALUES ((select max(id) from public.food where name = 'Fat Pork'), (select max(id) from public.category where name = 'Sandwiches'));
INSERT INTO public.ingredient (name) VALUES ('Bread') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.ingredient_in_food (food_id, ingredient_id) VALUES ((select max(id) from public.food where name = 'Fat Pork'), (select max(id) from public.ingredient where name = 'Bread'));
INSERT INTO public.ingredient (name) VALUES ('Pulled Pork') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.ingredient_in_food (food_id, ingredient_id) VALUES ((select max(id) from public.food where name = 'Fat Pork'), (select max(id) from public.ingredient where name = 'Pulled Pork'));
INSERT INTO public.ingredient (name) VALUES ('BBQ sauce') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.ingredient_in_food (food_id, ingredient_id) VALUES ((select max(id) from public.food where name = 'Fat Pork'), (select max(id) from public.ingredient where name = 'BBQ sauce'));
INSERT INTO public.ingredient (name) VALUES ('Coleslaw') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.ingredient_in_food (food_id, ingredient_id) VALUES ((select max(id) from public.food where name = 'Fat Pork'), (select max(id) from public.ingredient where name = 'Coleslaw'));
INSERT INTO public.ingredient (name) VALUES ('Sriracha Mayo') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.ingredient_in_food (food_id, ingredient_id) VALUES ((select max(id) from public.food where name = 'Fat Pork'), (select max(id) from public.ingredient where name = 'Sriracha Mayo'));
INSERT INTO public.food (name, photo, price, restaurant_id) VALUES ('Chicken Pesto', 'https://korpa.ba/product_uploads/fcxHDPhJbBP9nICn7UEkPQdSeOOGJ5W9.jpg', 270, (select max(id) from public.restaurant where name = 'Fat Kitchen Bistro'));
INSERT INTO public.category_of_food (food_id, category_id) VALUES ((select max(id) from public.food where name = 'Chicken Pesto'), (select max(id) from public.category where name = 'Sandwiches'));
INSERT INTO public.ingredient (name) VALUES ('Bread') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.ingredient_in_food (food_id, ingredient_id) VALUES ((select max(id) from public.food where name = 'Chicken Pesto'), (select max(id) from public.ingredient where name = 'Bread'));
INSERT INTO public.ingredient (name) VALUES ('Chicken in pesto sauce') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.ingredient_in_food (food_id, ingredient_id) VALUES ((select max(id) from public.food where name = 'Chicken Pesto'), (select max(id) from public.ingredient where name = 'Chicken in pesto sauce'));
INSERT INTO public.ingredient (name) VALUES ('Fresh tomato') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.ingredient_in_food (food_id, ingredient_id) VALUES ((select max(id) from public.food where name = 'Chicken Pesto'), (select max(id) from public.ingredient where name = 'Fresh tomato'));
INSERT INTO public.ingredient (name) VALUES ('Mozzarella') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.ingredient_in_food (food_id, ingredient_id) VALUES ((select max(id) from public.food where name = 'Chicken Pesto'), (select max(id) from public.ingredient where name = 'Mozzarella'));
INSERT INTO public.ingredient (name) VALUES ('Baby rocket') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.ingredient_in_food (food_id, ingredient_id) VALUES ((select max(id) from public.food where name = 'Chicken Pesto'), (select max(id) from public.ingredient where name = 'Baby rocket'));
INSERT INTO public.ingredient (name) VALUES ('Sriracha Mayo') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.ingredient_in_food (food_id, ingredient_id) VALUES ((select max(id) from public.food where name = 'Chicken Pesto'), (select max(id) from public.ingredient where name = 'Sriracha Mayo'));
INSERT INTO public.food (name, photo, price, restaurant_id) VALUES ('Fat Cheeseburger', 'https://korpa.ba/product_uploads/YqhY2iAUhK1TLOvGt3i2BIPw1qWTGuR1.jpg', 320, (select max(id) from public.restaurant where name = 'Fat Kitchen Bistro'));
INSERT INTO public.category_of_food (food_id, category_id) VALUES ((select max(id) from public.food where name = 'Fat Cheeseburger'), (select max(id) from public.category where name = 'Sandwiches'));
INSERT INTO public.ingredient (name) VALUES ('Bread') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.ingredient_in_food (food_id, ingredient_id) VALUES ((select max(id) from public.food where name = 'Fat Cheeseburger'), (select max(id) from public.ingredient where name = 'Bread'));
INSERT INTO public.ingredient (name) VALUES ('Beef burger') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.ingredient_in_food (food_id, ingredient_id) VALUES ((select max(id) from public.food where name = 'Fat Cheeseburger'), (select max(id) from public.ingredient where name = 'Beef burger'));
INSERT INTO public.ingredient (name) VALUES ('Pickles') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.ingredient_in_food (food_id, ingredient_id) VALUES ((select max(id) from public.food where name = 'Fat Cheeseburger'), (select max(id) from public.ingredient where name = 'Pickles'));
INSERT INTO public.ingredient (name) VALUES ('Iceberg') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.ingredient_in_food (food_id, ingredient_id) VALUES ((select max(id) from public.food where name = 'Fat Cheeseburger'), (select max(id) from public.ingredient where name = 'Iceberg'));
INSERT INTO public.ingredient (name) VALUES ('Cheddar cheese') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.ingredient_in_food (food_id, ingredient_id) VALUES ((select max(id) from public.food where name = 'Fat Cheeseburger'), (select max(id) from public.ingredient where name = 'Cheddar cheese'));
INSERT INTO public.ingredient (name) VALUES ('Pickled red onion') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.ingredient_in_food (food_id, ingredient_id) VALUES ((select max(id) from public.food where name = 'Fat Cheeseburger'), (select max(id) from public.ingredient where name = 'Pickled red onion'));
INSERT INTO public.ingredient (name) VALUES ('Sriraca mayo') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.ingredient_in_food (food_id, ingredient_id) VALUES ((select max(id) from public.food where name = 'Fat Cheeseburger'), (select max(id) from public.ingredient where name = 'Sriraca mayo'));
INSERT INTO public.food (name, photo, price, restaurant_id) VALUES ('Black Angus Smash Burger', 'https://korpa.ba/product_uploads/IvBoSVF1w1dmOjmmPhIpXf25nYc225co.jpg', 360, (select max(id) from public.restaurant where name = 'Fat Kitchen Bistro'));
INSERT INTO public.category_of_food (food_id, category_id) VALUES ((select max(id) from public.food where name = 'Black Angus Smash Burger'), (select max(id) from public.category where name = 'Sandwiches'));
INSERT INTO public.ingredient (name) VALUES ('Bun') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.ingredient_in_food (food_id, ingredient_id) VALUES ((select max(id) from public.food where name = 'Black Angus Smash Burger'), (select max(id) from public.ingredient where name = 'Bun'));
INSERT INTO public.ingredient (name) VALUES ('2 Black Angus patties') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.ingredient_in_food (food_id, ingredient_id) VALUES ((select max(id) from public.food where name = 'Black Angus Smash Burger'), (select max(id) from public.ingredient where name = '2 Black Angus patties'));
INSERT INTO public.ingredient (name) VALUES ('smoked cheese') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.ingredient_in_food (food_id, ingredient_id) VALUES ((select max(id) from public.food where name = 'Black Angus Smash Burger'), (select max(id) from public.ingredient where name = 'smoked cheese'));
INSERT INTO public.ingredient (name) VALUES ('pickles') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.ingredient_in_food (food_id, ingredient_id) VALUES ((select max(id) from public.food where name = 'Black Angus Smash Burger'), (select max(id) from public.ingredient where name = 'pickles'));
INSERT INTO public.ingredient (name) VALUES ('red pepper') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.ingredient_in_food (food_id, ingredient_id) VALUES ((select max(id) from public.food where name = 'Black Angus Smash Burger'), (select max(id) from public.ingredient where name = 'red pepper'));
INSERT INTO public.ingredient (name) VALUES ('iceberg lettuce') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.ingredient_in_food (food_id, ingredient_id) VALUES ((select max(id) from public.food where name = 'Black Angus Smash Burger'), (select max(id) from public.ingredient where name = 'iceberg lettuce'));
INSERT INTO public.ingredient (name) VALUES ('sriracha mayo') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.ingredient_in_food (food_id, ingredient_id) VALUES ((select max(id) from public.food where name = 'Black Angus Smash Burger'), (select max(id) from public.ingredient where name = 'sriracha mayo'));
INSERT INTO public.food (name, photo, price, restaurant_id) VALUES ('Mac & Cheese', 'https://korpa.ba/product_uploads/VTzr3J1EfF4YbcZ1jmcNjPuQxuvzslbI.jpg', 230, (select max(id) from public.restaurant where name = 'Fat Kitchen Bistro'));
INSERT INTO public.category_of_food (food_id, category_id) VALUES ((select max(id) from public.food where name = 'Mac & Cheese'), (select max(id) from public.category where name = 'Sandwiches'));
INSERT INTO public.ingredient (name) VALUES ('Macaroni') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.ingredient_in_food (food_id, ingredient_id) VALUES ((select max(id) from public.food where name = 'Mac & Cheese'), (select max(id) from public.ingredient where name = 'Macaroni'));
INSERT INTO public.ingredient (name) VALUES ('cheese sauce') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.ingredient_in_food (food_id, ingredient_id) VALUES ((select max(id) from public.food where name = 'Mac & Cheese'), (select max(id) from public.ingredient where name = 'cheese sauce'));
INSERT INTO public.ingredient (name) VALUES ('mozzarella') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.ingredient_in_food (food_id, ingredient_id) VALUES ((select max(id) from public.food where name = 'Mac & Cheese'), (select max(id) from public.ingredient where name = 'mozzarella'));
INSERT INTO public.ingredient (name) VALUES ('cheddar cheese') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.ingredient_in_food (food_id, ingredient_id) VALUES ((select max(id) from public.food where name = 'Mac & Cheese'), (select max(id) from public.ingredient where name = 'cheddar cheese'));
INSERT INTO public.food (name, photo, price, restaurant_id) VALUES ('Chopped Cheese', 'https://korpa.ba/product_uploads/O7HtKkCWCUjtv4Kh2nO61Q7Tci6Ok0Vd.jpg', 350, (select max(id) from public.restaurant where name = 'Fat Kitchen Bistro'));
INSERT INTO public.category_of_food (food_id, category_id) VALUES ((select max(id) from public.food where name = 'Chopped Cheese'), (select max(id) from public.category where name = 'Sandwiches'));
INSERT INTO public.ingredient (name) VALUES ('Bavarian baguette') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.ingredient_in_food (food_id, ingredient_id) VALUES ((select max(id) from public.food where name = 'Chopped Cheese'), (select max(id) from public.ingredient where name = 'Bavarian baguette'));
INSERT INTO public.ingredient (name) VALUES ('beef') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.ingredient_in_food (food_id, ingredient_id) VALUES ((select max(id) from public.food where name = 'Chopped Cheese'), (select max(id) from public.ingredient where name = 'beef'));
INSERT INTO public.ingredient (name) VALUES ('mozzarella') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.ingredient_in_food (food_id, ingredient_id) VALUES ((select max(id) from public.food where name = 'Chopped Cheese'), (select max(id) from public.ingredient where name = 'mozzarella'));
INSERT INTO public.ingredient (name) VALUES ('cheddar cheese') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.ingredient_in_food (food_id, ingredient_id) VALUES ((select max(id) from public.food where name = 'Chopped Cheese'), (select max(id) from public.ingredient where name = 'cheddar cheese'));
INSERT INTO public.ingredient (name) VALUES ('red pepper') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.ingredient_in_food (food_id, ingredient_id) VALUES ((select max(id) from public.food where name = 'Chopped Cheese'), (select max(id) from public.ingredient where name = 'red pepper'));
INSERT INTO public.ingredient (name) VALUES ('pickled red onion') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.ingredient_in_food (food_id, ingredient_id) VALUES ((select max(id) from public.food where name = 'Chopped Cheese'), (select max(id) from public.ingredient where name = 'pickled red onion'));
INSERT INTO public.ingredient (name) VALUES ('iceberg lettuce') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.ingredient_in_food (food_id, ingredient_id) VALUES ((select max(id) from public.food where name = 'Chopped Cheese'), (select max(id) from public.ingredient where name = 'iceberg lettuce'));
INSERT INTO public.food (name, photo, price, restaurant_id) VALUES ('Vegan Special Burger', 'https://korpa.ba/product_uploads/fbiO9IXBewVfcAMEYM38783bjJgQJXxv.jpg', 320, (select max(id) from public.restaurant where name = 'Fat Kitchen Bistro'));
INSERT INTO public.category_of_food (food_id, category_id) VALUES ((select max(id) from public.food where name = 'Vegan Special Burger'), (select max(id) from public.category where name = 'Sandwiches'));
INSERT INTO public.ingredient (name) VALUES ('Ciabatta') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.ingredient_in_food (food_id, ingredient_id) VALUES ((select max(id) from public.food where name = 'Vegan Special Burger'), (select max(id) from public.ingredient where name = 'Ciabatta'));
INSERT INTO public.ingredient (name) VALUES ('vegan patty') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.ingredient_in_food (food_id, ingredient_id) VALUES ((select max(id) from public.food where name = 'Vegan Special Burger'), (select max(id) from public.ingredient where name = 'vegan patty'));
INSERT INTO public.ingredient (name) VALUES ('eggplant') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.ingredient_in_food (food_id, ingredient_id) VALUES ((select max(id) from public.food where name = 'Vegan Special Burger'), (select max(id) from public.ingredient where name = 'eggplant'));
INSERT INTO public.ingredient (name) VALUES ('pickled red onions') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.ingredient_in_food (food_id, ingredient_id) VALUES ((select max(id) from public.food where name = 'Vegan Special Burger'), (select max(id) from public.ingredient where name = 'pickled red onions'));
INSERT INTO public.ingredient (name) VALUES ('mixed salad') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.ingredient_in_food (food_id, ingredient_id) VALUES ((select max(id) from public.food where name = 'Vegan Special Burger'), (select max(id) from public.ingredient where name = 'mixed salad'));
INSERT INTO public.ingredient (name) VALUES ('sriracha mayo') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.ingredient_in_food (food_id, ingredient_id) VALUES ((select max(id) from public.food where name = 'Vegan Special Burger'), (select max(id) from public.ingredient where name = 'sriracha mayo'));
INSERT INTO public.food (name, photo, price, restaurant_id) VALUES ('King Angus', 'https://korpa.ba/product_uploads/vN1gvJ1J1gvjv2yUhZ3439SWhNfE6naK.jpg', 390, (select max(id) from public.restaurant where name = 'Fat Kitchen Bistro'));
INSERT INTO public.category_of_food (food_id, category_id) VALUES ((select max(id) from public.food where name = 'King Angus'), (select max(id) from public.category where name = 'Sandwiches'));
INSERT INTO public.ingredient (name) VALUES ('Bun') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.ingredient_in_food (food_id, ingredient_id) VALUES ((select max(id) from public.food where name = 'King Angus'), (select max(id) from public.ingredient where name = 'Bun'));
INSERT INTO public.ingredient (name) VALUES ('Black Angus patty (medium rare)') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.ingredient_in_food (food_id, ingredient_id) VALUES ((select max(id) from public.food where name = 'King Angus'), (select max(id) from public.ingredient where name = 'Black Angus patty (medium rare)'));
INSERT INTO public.ingredient (name) VALUES ('bacon') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.ingredient_in_food (food_id, ingredient_id) VALUES ((select max(id) from public.food where name = 'King Angus'), (select max(id) from public.ingredient where name = 'bacon'));
INSERT INTO public.ingredient (name) VALUES ('cheddar cheese') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.ingredient_in_food (food_id, ingredient_id) VALUES ((select max(id) from public.food where name = 'King Angus'), (select max(id) from public.ingredient where name = 'cheddar cheese'));
INSERT INTO public.ingredient (name) VALUES ('smoked cheese') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.ingredient_in_food (food_id, ingredient_id) VALUES ((select max(id) from public.food where name = 'King Angus'), (select max(id) from public.ingredient where name = 'smoked cheese'));
INSERT INTO public.ingredient (name) VALUES ('pickles') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.ingredient_in_food (food_id, ingredient_id) VALUES ((select max(id) from public.food where name = 'King Angus'), (select max(id) from public.ingredient where name = 'pickles'));
INSERT INTO public.ingredient (name) VALUES ('mustard') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.ingredient_in_food (food_id, ingredient_id) VALUES ((select max(id) from public.food where name = 'King Angus'), (select max(id) from public.ingredient where name = 'mustard'));
INSERT INTO public.ingredient (name) VALUES ('sriracha mayo') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.ingredient_in_food (food_id, ingredient_id) VALUES ((select max(id) from public.food where name = 'King Angus'), (select max(id) from public.ingredient where name = 'sriracha mayo'));
INSERT INTO public.food (name, photo, price, restaurant_id) VALUES ('Vegan Crunch Wrap', 'https://korpa.ba/product_uploads/yEtjv2IEukq8mxeovlhql7xo3txh4AkS.jpg', 320, (select max(id) from public.restaurant where name = 'Fat Kitchen Bistro'));
INSERT INTO public.category_of_food (food_id, category_id) VALUES ((select max(id) from public.food where name = 'Vegan Crunch Wrap'), (select max(id) from public.category where name = 'Sandwiches'));
INSERT INTO public.ingredient (name) VALUES ('Крцкави Vegan Nudgets') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.ingredient_in_food (food_id, ingredient_id) VALUES ((select max(id) from public.food where name = 'Vegan Crunch Wrap'), (select max(id) from public.ingredient where name = 'Крцкави Vegan Nudgets'));
INSERT INTO public.ingredient (name) VALUES ('свеж домат') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.ingredient_in_food (food_id, ingredient_id) VALUES ((select max(id) from public.food where name = 'Vegan Crunch Wrap'), (select max(id) from public.ingredient where name = 'свеж домат'));
INSERT INTO public.ingredient (name) VALUES ('микс салата') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.ingredient_in_food (food_id, ingredient_id) VALUES ((select max(id) from public.food where name = 'Vegan Crunch Wrap'), (select max(id) from public.ingredient where name = 'микс салата'));
INSERT INTO public.ingredient (name) VALUES ('Fat fries') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.ingredient_in_food (food_id, ingredient_id) VALUES ((select max(id) from public.food where name = 'Vegan Crunch Wrap'), (select max(id) from public.ingredient where name = 'Fat fries'));
INSERT INTO public.ingredient (name) VALUES ('закиселено кромитче') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.ingredient_in_food (food_id, ingredient_id) VALUES ((select max(id) from public.food where name = 'Vegan Crunch Wrap'), (select max(id) from public.ingredient where name = 'закиселено кромитче'));
INSERT INTO public.ingredient (name) VALUES ('spicy cilantro сос') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.ingredient_in_food (food_id, ingredient_id) VALUES ((select max(id) from public.food where name = 'Vegan Crunch Wrap'), (select max(id) from public.ingredient where name = 'spicy cilantro сос'));
INSERT INTO public.ingredient (name) VALUES ('ананас салса за освежување') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.ingredient_in_food (food_id, ingredient_id) VALUES ((select max(id) from public.food where name = 'Vegan Crunch Wrap'), (select max(id) from public.ingredient where name = 'ананас салса за освежување'));
INSERT INTO public.ingredient (name) VALUES ('посен срирача мајо') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.ingredient_in_food (food_id, ingredient_id) VALUES ((select max(id) from public.food where name = 'Vegan Crunch Wrap'), (select max(id) from public.ingredient where name = 'посен срирача мајо'));
INSERT INTO public.food (name, photo, price, restaurant_id) VALUES ('Double Smash Burger', 'https://korpa.ba/product_uploads/qoJS3KplLoQd5WKzfm3jS7L5T6EAYTun.jpg', 290, (select max(id) from public.restaurant where name = 'Fat Kitchen Bistro'));
INSERT INTO public.category_of_food (food_id, category_id) VALUES ((select max(id) from public.food where name = 'Double Smash Burger'), (select max(id) from public.category where name = 'Sandwiches'));
INSERT INTO public.ingredient (name) VALUES ('Лепче') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.ingredient_in_food (food_id, ingredient_id) VALUES ((select max(id) from public.food where name = 'Double Smash Burger'), (select max(id) from public.ingredient where name = 'Лепче'));
INSERT INTO public.ingredient (name) VALUES ('2x јунешки smash плескавици') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.ingredient_in_food (food_id, ingredient_id) VALUES ((select max(id) from public.food where name = 'Double Smash Burger'), (select max(id) from public.ingredient where name = '2x јунешки smash плескавици'));
INSERT INTO public.ingredient (name) VALUES ('2x едамер') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.ingredient_in_food (food_id, ingredient_id) VALUES ((select max(id) from public.food where name = 'Double Smash Burger'), (select max(id) from public.ingredient where name = '2x едамер'));
INSERT INTO public.ingredient (name) VALUES ('кисели краставички') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.ingredient_in_food (food_id, ingredient_id) VALUES ((select max(id) from public.food where name = 'Double Smash Burger'), (select max(id) from public.ingredient where name = 'кисели краставички'));
INSERT INTO public.ingredient (name) VALUES ('црвено кромитче') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.ingredient_in_food (food_id, ingredient_id) VALUES ((select max(id) from public.food where name = 'Double Smash Burger'), (select max(id) from public.ingredient where name = 'црвено кромитче'));
INSERT INTO public.ingredient (name) VALUES ('Heinz кечап') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.ingredient_in_food (food_id, ingredient_id) VALUES ((select max(id) from public.food where name = 'Double Smash Burger'), (select max(id) from public.ingredient where name = 'Heinz кечап'));
INSERT INTO public.ingredient (name) VALUES ('Heinz сенф') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.ingredient_in_food (food_id, ingredient_id) VALUES ((select max(id) from public.food where name = 'Double Smash Burger'), (select max(id) from public.ingredient where name = 'Heinz сенф'));
insert into public.category (name, photo) VALUES ('Salads', '/') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.food (name, photo, price, restaurant_id) VALUES ('Salad Chicken Pesto', 'https://korpa.ba/product_uploads/As8YfC8SvskIMSHwBA8ly81MvZb0m5HZ.jpg', 290, (select max(id) from public.restaurant where name = 'Fat Kitchen Bistro'));
INSERT INTO public.category_of_food (food_id, category_id) VALUES ((select max(id) from public.food where name = 'Salad Chicken Pesto'), (select max(id) from public.category where name = 'Salads'));
INSERT INTO public.ingredient (name) VALUES ('Mix salad') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.ingredient_in_food (food_id, ingredient_id) VALUES ((select max(id) from public.food where name = 'Salad Chicken Pesto'), (select max(id) from public.ingredient where name = 'Mix salad'));
INSERT INTO public.ingredient (name) VALUES ('Chicken in pesto sauce') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.ingredient_in_food (food_id, ingredient_id) VALUES ((select max(id) from public.food where name = 'Salad Chicken Pesto'), (select max(id) from public.ingredient where name = 'Chicken in pesto sauce'));
INSERT INTO public.ingredient (name) VALUES ('Parmesan') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.ingredient_in_food (food_id, ingredient_id) VALUES ((select max(id) from public.food where name = 'Salad Chicken Pesto'), (select max(id) from public.ingredient where name = 'Parmesan'));
INSERT INTO public.ingredient (name) VALUES ('Sherry tomato') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.ingredient_in_food (food_id, ingredient_id) VALUES ((select max(id) from public.food where name = 'Salad Chicken Pesto'), (select max(id) from public.ingredient where name = 'Sherry tomato'));
INSERT INTO public.ingredient (name) VALUES ('Dried cranberry') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.ingredient_in_food (food_id, ingredient_id) VALUES ((select max(id) from public.food where name = 'Salad Chicken Pesto'), (select max(id) from public.ingredient where name = 'Dried cranberry'));
INSERT INTO public.ingredient (name) VALUES ('Walnuts') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.ingredient_in_food (food_id, ingredient_id) VALUES ((select max(id) from public.food where name = 'Salad Chicken Pesto'), (select max(id) from public.ingredient where name = 'Walnuts'));
INSERT INTO public.ingredient (name) VALUES ('Olive oil') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.ingredient_in_food (food_id, ingredient_id) VALUES ((select max(id) from public.food where name = 'Salad Chicken Pesto'), (select max(id) from public.ingredient where name = 'Olive oil'));
INSERT INTO public.ingredient (name) VALUES ('Balsamic') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.ingredient_in_food (food_id, ingredient_id) VALUES ((select max(id) from public.food where name = 'Salad Chicken Pesto'), (select max(id) from public.ingredient where name = 'Balsamic'));
INSERT INTO public.food (name, photo, price, restaurant_id) VALUES ('Fat Salad', 'https://korpa.ba/product_uploads/JV0yJFfUYHoPRuPVf2dlMw6xNNWKW5Zp.jpg', 270, (select max(id) from public.restaurant where name = 'Fat Kitchen Bistro'));
INSERT INTO public.category_of_food (food_id, category_id) VALUES ((select max(id) from public.food where name = 'Fat Salad'), (select max(id) from public.category where name = 'Salads'));
INSERT INTO public.ingredient (name) VALUES ('Mix salad') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.ingredient_in_food (food_id, ingredient_id) VALUES ((select max(id) from public.food where name = 'Fat Salad'), (select max(id) from public.ingredient where name = 'Mix salad'));
INSERT INTO public.ingredient (name) VALUES ('Roasted beet') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.ingredient_in_food (food_id, ingredient_id) VALUES ((select max(id) from public.food where name = 'Fat Salad'), (select max(id) from public.ingredient where name = 'Roasted beet'));
INSERT INTO public.ingredient (name) VALUES ('Walnuts') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.ingredient_in_food (food_id, ingredient_id) VALUES ((select max(id) from public.food where name = 'Fat Salad'), (select max(id) from public.ingredient where name = 'Walnuts'));
INSERT INTO public.ingredient (name) VALUES ('Gorgonzola cheese') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.ingredient_in_food (food_id, ingredient_id) VALUES ((select max(id) from public.food where name = 'Fat Salad'), (select max(id) from public.ingredient where name = 'Gorgonzola cheese'));
INSERT INTO public.ingredient (name) VALUES ('Dried cranberry') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.ingredient_in_food (food_id, ingredient_id) VALUES ((select max(id) from public.food where name = 'Fat Salad'), (select max(id) from public.ingredient where name = 'Dried cranberry'));
INSERT INTO public.ingredient (name) VALUES ('Sesame') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.ingredient_in_food (food_id, ingredient_id) VALUES ((select max(id) from public.food where name = 'Fat Salad'), (select max(id) from public.ingredient where name = 'Sesame'));
INSERT INTO public.ingredient (name) VALUES ('Olive oil') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.ingredient_in_food (food_id, ingredient_id) VALUES ((select max(id) from public.food where name = 'Fat Salad'), (select max(id) from public.ingredient where name = 'Olive oil'));
INSERT INTO public.ingredient (name) VALUES ('Balsamicо') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.ingredient_in_food (food_id, ingredient_id) VALUES ((select max(id) from public.food where name = 'Fat Salad'), (select max(id) from public.ingredient where name = 'Balsamicо'));
INSERT INTO public.food (name, photo, price, restaurant_id) VALUES ('Mini Salad', 'https://korpa.ba/product_uploads/xtYejGyCLTpkRbBhBwlhYO7ZRSRqOzbf.jpg', 100, (select max(id) from public.restaurant where name = 'Fat Kitchen Bistro'));
INSERT INTO public.category_of_food (food_id, category_id) VALUES ((select max(id) from public.food where name = 'Mini Salad'), (select max(id) from public.category where name = 'Salads'));
INSERT INTO public.ingredient (name) VALUES ('Mix salad') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.ingredient_in_food (food_id, ingredient_id) VALUES ((select max(id) from public.food where name = 'Mini Salad'), (select max(id) from public.ingredient where name = 'Mix salad'));
INSERT INTO public.ingredient (name) VALUES ('Sherry tomato') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.ingredient_in_food (food_id, ingredient_id) VALUES ((select max(id) from public.food where name = 'Mini Salad'), (select max(id) from public.ingredient where name = 'Sherry tomato'));
INSERT INTO public.ingredient (name) VALUES ('Parmesan') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.ingredient_in_food (food_id, ingredient_id) VALUES ((select max(id) from public.food where name = 'Mini Salad'), (select max(id) from public.ingredient where name = 'Parmesan'));
INSERT INTO public.food (name, photo, price, restaurant_id) VALUES ('Tuna Couscous', 'https://korpa.ba/product_uploads/wpe9gFvjIP6jdF7KvlT6iL8UMaM8n205.jpg', 290, (select max(id) from public.restaurant where name = 'Fat Kitchen Bistro'));
INSERT INTO public.category_of_food (food_id, category_id) VALUES ((select max(id) from public.food where name = 'Tuna Couscous'), (select max(id) from public.category where name = 'Salads'));
INSERT INTO public.ingredient (name) VALUES ('Туна') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.ingredient_in_food (food_id, ingredient_id) VALUES ((select max(id) from public.food where name = 'Tuna Couscous'), (select max(id) from public.ingredient where name = 'Туна'));
INSERT INTO public.ingredient (name) VALUES ('кус кус') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.ingredient_in_food (food_id, ingredient_id) VALUES ((select max(id) from public.food where name = 'Tuna Couscous'), (select max(id) from public.ingredient where name = 'кус кус'));
INSERT INTO public.ingredient (name) VALUES ('варено јајце') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.ingredient_in_food (food_id, ingredient_id) VALUES ((select max(id) from public.food where name = 'Tuna Couscous'), (select max(id) from public.ingredient where name = 'варено јајце'));
INSERT INTO public.ingredient (name) VALUES ('микс салата') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.ingredient_in_food (food_id, ingredient_id) VALUES ((select max(id) from public.food where name = 'Tuna Couscous'), (select max(id) from public.ingredient where name = 'микс салата'));
INSERT INTO public.ingredient (name) VALUES ('зелка') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.ingredient_in_food (food_id, ingredient_id) VALUES ((select max(id) from public.food where name = 'Tuna Couscous'), (select max(id) from public.ingredient where name = 'зелка'));
INSERT INTO public.ingredient (name) VALUES ('пченка') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.ingredient_in_food (food_id, ingredient_id) VALUES ((select max(id) from public.food where name = 'Tuna Couscous'), (select max(id) from public.ingredient where name = 'пченка'));
INSERT INTO public.ingredient (name) VALUES ('домат') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.ingredient_in_food (food_id, ingredient_id) VALUES ((select max(id) from public.food where name = 'Tuna Couscous'), (select max(id) from public.ingredient where name = 'домат'));
INSERT INTO public.ingredient (name) VALUES ('маслиново масло') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.ingredient_in_food (food_id, ingredient_id) VALUES ((select max(id) from public.food where name = 'Tuna Couscous'), (select max(id) from public.ingredient where name = 'маслиново масло'));
INSERT INTO public.ingredient (name) VALUES ('зелен сос') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.ingredient_in_food (food_id, ingredient_id) VALUES ((select max(id) from public.food where name = 'Tuna Couscous'), (select max(id) from public.ingredient where name = 'зелен сос'));
insert into public.category (name, photo) VALUES ('Fries', '/') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.food (name, photo, price, restaurant_id) VALUES ('Seasoned Crinkle Cut', 'https://korpa.ba/product_uploads/VNrueukLDkvkyTFRGulWmPyPUE3yvMMA.jpg', 80, (select max(id) from public.restaurant where name = 'Fat Kitchen Bistro'));
INSERT INTO public.category_of_food (food_id, category_id) VALUES ((select max(id) from public.food where name = 'Seasoned Crinkle Cut'), (select max(id) from public.category where name = 'Fries'));
INSERT INTO public.food (name, photo, price, restaurant_id) VALUES ('Seasoned Crinkle Cut - Size M (250gr)', 'https://korpa.ba/product_uploads/9ynlRi9JUmLq2Fh5cSboVyFXtBuRaqEA.jpg', 150, (select max(id) from public.restaurant where name = 'Fat Kitchen Bistro'));
INSERT INTO public.category_of_food (food_id, category_id) VALUES ((select max(id) from public.food where name = 'Seasoned Crinkle Cut - Size M (250gr)'), (select max(id) from public.category where name = 'Fries'));
INSERT INTO public.food (name, photo, price, restaurant_id) VALUES ('Seasoned Crinkle Cut - Size L (450gr)', 'https://korpa.ba/product_uploads/hIJ0CZupK3xZM899fd0aT8qZEJy7IWdx.jpg', 250, (select max(id) from public.restaurant where name = 'Fat Kitchen Bistro'));
INSERT INTO public.category_of_food (food_id, category_id) VALUES ((select max(id) from public.food where name = 'Seasoned Crinkle Cut - Size L (450gr)'), (select max(id) from public.category where name = 'Fries'));
insert into public.category (name, photo) VALUES ('Sides', '/') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.food (name, photo, price, restaurant_id) VALUES ('Bacon', 'None', 50, (select max(id) from public.restaurant where name = 'Fat Kitchen Bistro'));
INSERT INTO public.category_of_food (food_id, category_id) VALUES ((select max(id) from public.food where name = 'Bacon'), (select max(id) from public.category where name = 'Sides'));
INSERT INTO public.food (name, photo, price, restaurant_id) VALUES ('Cheese', 'None', 50, (select max(id) from public.restaurant where name = 'Fat Kitchen Bistro'));
INSERT INTO public.category_of_food (food_id, category_id) VALUES ((select max(id) from public.food where name = 'Cheese'), (select max(id) from public.category where name = 'Sides'));
INSERT INTO public.food (name, photo, price, restaurant_id) VALUES ('Cheese sauce', 'None', 60, (select max(id) from public.restaurant where name = 'Fat Kitchen Bistro'));
INSERT INTO public.category_of_food (food_id, category_id) VALUES ((select max(id) from public.food where name = 'Cheese sauce'), (select max(id) from public.category where name = 'Sides'));
INSERT INTO public.food (name, photo, price, restaurant_id) VALUES ('Срирача Мајо', 'None', 10, (select max(id) from public.restaurant where name = 'Fat Kitchen Bistro'));
INSERT INTO public.category_of_food (food_id, category_id) VALUES ((select max(id) from public.food where name = 'Срирача Мајо'), (select max(id) from public.category where name = 'Sides'));
INSERT INTO public.food (name, photo, price, restaurant_id) VALUES ('BBQ сос', 'None', 10, (select max(id) from public.restaurant where name = 'Fat Kitchen Bistro'));
INSERT INTO public.category_of_food (food_id, category_id) VALUES ((select max(id) from public.food where name = 'BBQ сос'), (select max(id) from public.category where name = 'Sides'));
insert into public.category (name, photo) VALUES ('Soups', '/') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.food (name, photo, price, restaurant_id) VALUES ('Beetroot Soup', 'https://korpa.ba/product_uploads/9r1Lhki6CFuuFxJ3CMepCz8H369EX9oQ.jpg', 160, (select max(id) from public.restaurant where name = 'Fat Kitchen Bistro'));
INSERT INTO public.category_of_food (food_id, category_id) VALUES ((select max(id) from public.food where name = 'Beetroot Soup'), (select max(id) from public.category where name = 'Soups'));
INSERT INTO public.food (name, photo, price, restaurant_id) VALUES ('Lentil Soup', 'https://korpa.ba/product_uploads/o1hgvTimbXFgrF207AxVgTD4OCsegU4p.jpg', 160, (select max(id) from public.restaurant where name = 'Fat Kitchen Bistro'));
INSERT INTO public.category_of_food (food_id, category_id) VALUES ((select max(id) from public.food where name = 'Lentil Soup'), (select max(id) from public.category where name = 'Soups'));
INSERT INTO public.food (name, photo, price, restaurant_id) VALUES ('Pumpkin Soup', 'https://korpa.ba/product_uploads/SMoR4zzLSvuIuR88thvescZWSkiKrGYf.jpg', 160, (select max(id) from public.restaurant where name = 'Fat Kitchen Bistro'));
INSERT INTO public.category_of_food (food_id, category_id) VALUES ((select max(id) from public.food where name = 'Pumpkin Soup'), (select max(id) from public.category where name = 'Soups'));
INSERT INTO public.food (name, photo, price, restaurant_id) VALUES ('Broccoli & Spinach Soup', 'https://korpa.ba/product_uploads/cfuAUGoxjPmHvH9xkGWUq36YE8GdOhpC.jpg', 160, (select max(id) from public.restaurant where name = 'Fat Kitchen Bistro'));
INSERT INTO public.category_of_food (food_id, category_id) VALUES ((select max(id) from public.food where name = 'Broccoli & Spinach Soup'), (select max(id) from public.category where name = 'Soups'));
INSERT INTO public.food (name, photo, price, restaurant_id) VALUES ('Pea Soup', 'https://korpa.ba/product_uploads/CFL5dJl2lMioNGcX4mTAZj7lr6mo0u18.jpg', 160, (select max(id) from public.restaurant where name = 'Fat Kitchen Bistro'));
INSERT INTO public.category_of_food (food_id, category_id) VALUES ((select max(id) from public.food where name = 'Pea Soup'), (select max(id) from public.category where name = 'Soups'));
insert into public.category (name, photo) VALUES ('Desserts', '/') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.food (name, photo, price, restaurant_id) VALUES ('Desert', 'https://korpa.ba/product_uploads/Z8FrlPNFO9OQDnrijJ31wyqklPa2SKEV.jpg', 150, (select max(id) from public.restaurant where name = 'Fat Kitchen Bistro'));
INSERT INTO public.category_of_food (food_id, category_id) VALUES ((select max(id) from public.food where name = 'Desert'), (select max(id) from public.category where name = 'Desserts'));
INSERT INTO public.food (name, photo, price, restaurant_id) VALUES ('Благо на денот #2', 'https://korpa.ba/product_uploads/DQo7BUVdt7iHpfKSUbtEceu3Bd9SD1Yx.jpg', 120, (select max(id) from public.restaurant where name = 'Fat Kitchen Bistro'));
INSERT INTO public.category_of_food (food_id, category_id) VALUES ((select max(id) from public.food where name = 'Благо на денот #2'), (select max(id) from public.category where name = 'Desserts'));
INSERT INTO public.food (name, photo, price, restaurant_id) VALUES ('Мафин', 'https://korpa.ba/product_uploads/QpE2eDKj2JKLJfhus3mD67W4wiuaGpmb.jpg', 70, (select max(id) from public.restaurant where name = 'Fat Kitchen Bistro'));
INSERT INTO public.category_of_food (food_id, category_id) VALUES ((select max(id) from public.food where name = 'Мафин'), (select max(id) from public.category where name = 'Desserts'));
INSERT INTO public.ingredient (name) VALUES ('Урми') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.ingredient_in_food (food_id, ingredient_id) VALUES ((select max(id) from public.food where name = 'Мафин'), (select max(id) from public.ingredient where name = 'Урми'));
INSERT INTO public.ingredient (name) VALUES ('ореви') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.ingredient_in_food (food_id, ingredient_id) VALUES ((select max(id) from public.food where name = 'Мафин'), (select max(id) from public.ingredient where name = 'ореви'));
INSERT INTO public.ingredient (name) VALUES ('чоколадо') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.ingredient_in_food (food_id, ingredient_id) VALUES ((select max(id) from public.food where name = 'Мафин'), (select max(id) from public.ingredient where name = 'чоколадо'));
INSERT INTO public.ingredient (name) VALUES ('јајца') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.ingredient_in_food (food_id, ingredient_id) VALUES ((select max(id) from public.food where name = 'Мафин'), (select max(id) from public.ingredient where name = 'јајца'));
INSERT INTO public.ingredient (name) VALUES ('путер') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.ingredient_in_food (food_id, ingredient_id) VALUES ((select max(id) from public.food where name = 'Мафин'), (select max(id) from public.ingredient where name = 'путер'));
INSERT INTO public.ingredient (name) VALUES ('масло') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.ingredient_in_food (food_id, ingredient_id) VALUES ((select max(id) from public.food where name = 'Мафин'), (select max(id) from public.ingredient where name = 'масло'));
INSERT INTO public.ingredient (name) VALUES ('брашно') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.ingredient_in_food (food_id, ingredient_id) VALUES ((select max(id) from public.food where name = 'Мафин'), (select max(id) from public.ingredient where name = 'брашно'));
INSERT INTO public.ingredient (name) VALUES ('шеќер') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.ingredient_in_food (food_id, ingredient_id) VALUES ((select max(id) from public.food where name = 'Мафин'), (select max(id) from public.ingredient where name = 'шеќер'));
INSERT INTO public.ingredient (name) VALUES ('ванила') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.ingredient_in_food (food_id, ingredient_id) VALUES ((select max(id) from public.food where name = 'Мафин'), (select max(id) from public.ingredient where name = 'ванила'));
INSERT INTO public.ingredient (name) VALUES ('цимет') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.ingredient_in_food (food_id, ingredient_id) VALUES ((select max(id) from public.food where name = 'Мафин'), (select max(id) from public.ingredient where name = 'цимет'));
INSERT INTO public.food (name, photo, price, restaurant_id) VALUES ('Chocolate Chip Cookie', 'https://korpa.ba/product_uploads/kTfMJlqu1ETmc9BbayKlnEQ3n7eyWnG5.jpg', 70, (select max(id) from public.restaurant where name = 'Fat Kitchen Bistro'));
INSERT INTO public.category_of_food (food_id, category_id) VALUES ((select max(id) from public.food where name = 'Chocolate Chip Cookie'), (select max(id) from public.category where name = 'Desserts'));
INSERT INTO public.ingredient (name) VALUES ('Брашно') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.ingredient_in_food (food_id, ingredient_id) VALUES ((select max(id) from public.food where name = 'Chocolate Chip Cookie'), (select max(id) from public.ingredient where name = 'Брашно'));
INSERT INTO public.ingredient (name) VALUES ('јајца') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.ingredient_in_food (food_id, ingredient_id) VALUES ((select max(id) from public.food where name = 'Chocolate Chip Cookie'), (select max(id) from public.ingredient where name = 'јајца'));
INSERT INTO public.ingredient (name) VALUES ('путер') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.ingredient_in_food (food_id, ingredient_id) VALUES ((select max(id) from public.food where name = 'Chocolate Chip Cookie'), (select max(id) from public.ingredient where name = 'путер'));
INSERT INTO public.ingredient (name) VALUES ('црно чоколадо') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.ingredient_in_food (food_id, ingredient_id) VALUES ((select max(id) from public.food where name = 'Chocolate Chip Cookie'), (select max(id) from public.ingredient where name = 'црно чоколадо'));
INSERT INTO public.ingredient (name) VALUES ('бело чоколадо') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.ingredient_in_food (food_id, ingredient_id) VALUES ((select max(id) from public.food where name = 'Chocolate Chip Cookie'), (select max(id) from public.ingredient where name = 'бело чоколадо'));
INSERT INTO public.ingredient (name) VALUES ('млечно чоколадо') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.ingredient_in_food (food_id, ingredient_id) VALUES ((select max(id) from public.food where name = 'Chocolate Chip Cookie'), (select max(id) from public.ingredient where name = 'млечно чоколадо'));
INSERT INTO public.ingredient (name) VALUES ('шеќер') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.ingredient_in_food (food_id, ingredient_id) VALUES ((select max(id) from public.food where name = 'Chocolate Chip Cookie'), (select max(id) from public.ingredient where name = 'шеќер'));
INSERT INTO public.ingredient (name) VALUES ('ванила екстракт') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.ingredient_in_food (food_id, ingredient_id) VALUES ((select max(id) from public.food where name = 'Chocolate Chip Cookie'), (select max(id) from public.ingredient where name = 'ванила екстракт'));
insert into public.category (name, photo) VALUES ('Drinks', '/') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.food (name, photo, price, restaurant_id) VALUES ('Coca Cola', 'https://korpa.ba/product_uploads/IRMyBFu8rvnodx1hWsLviPdwP4VCpBzv.jpg', 70, (select max(id) from public.restaurant where name = 'Fat Kitchen Bistro'));
INSERT INTO public.category_of_food (food_id, category_id) VALUES ((select max(id) from public.food where name = 'Coca Cola'), (select max(id) from public.category where name = 'Drinks'));
INSERT INTO public.food (name, photo, price, restaurant_id) VALUES ('Schweppes', 'https://korpa.ba/product_uploads/F5g9Dkqz8z1E9OfyYoPTyJUo09NhLDxq.png', 70, (select max(id) from public.restaurant where name = 'Fat Kitchen Bistro'));
INSERT INTO public.category_of_food (food_id, category_id) VALUES ((select max(id) from public.food where name = 'Schweppes'), (select max(id) from public.category where name = 'Drinks'));
INSERT INTO public.food (name, photo, price, restaurant_id) VALUES ('Water', 'https://korpa.ba/product_uploads/vdexAj73jwqmy13ZquIabt9LOJ5MjSzH.jpg', 50, (select max(id) from public.restaurant where name = 'Fat Kitchen Bistro'));
INSERT INTO public.category_of_food (food_id, category_id) VALUES ((select max(id) from public.food where name = 'Water'), (select max(id) from public.category where name = 'Drinks'));
INSERT INTO public.food (name, photo, price, restaurant_id) VALUES ('Skopsko beer', 'https://korpa.ba/product_uploads/TDiOPfooOwes2ZmowPVKFLvwghCdnYAb.PNG', 80, (select max(id) from public.restaurant where name = 'Fat Kitchen Bistro'));
INSERT INTO public.category_of_food (food_id, category_id) VALUES ((select max(id) from public.food where name = 'Skopsko beer'), (select max(id) from public.category where name = 'Drinks'));
INSERT INTO public.food (name, photo, price, restaurant_id) VALUES ('Skopsko Smooth beer', 'https://korpa.ba/product_uploads/dpm0jpGx0ZO436X6c1V5j2TSVNsbff6J.png', 80, (select max(id) from public.restaurant where name = 'Fat Kitchen Bistro'));
INSERT INTO public.category_of_food (food_id, category_id) VALUES ((select max(id) from public.food where name = 'Skopsko Smooth beer'), (select max(id) from public.category where name = 'Drinks'));
INSERT INTO public.food (name, photo, price, restaurant_id) VALUES ('Heineken', 'https://korpa.ba/product_uploads/QiqyUImaI7TEfMk8r4EilxWwPC4T9gNZ.jpg', 100, (select max(id) from public.restaurant where name = 'Fat Kitchen Bistro'));
INSERT INTO public.category_of_food (food_id, category_id) VALUES ((select max(id) from public.food where name = 'Heineken'), (select max(id) from public.category where name = 'Drinks'));
INSERT INTO public.food (name, photo, price, restaurant_id) VALUES ('Foks 0.33', 'https://korpa.ba/product_uploads/8LeDS1RtVohBtUcg2U9DO2uPdrC5fRPm.jpg', 180, (select max(id) from public.restaurant where name = 'Fat Kitchen Bistro'));
INSERT INTO public.category_of_food (food_id, category_id) VALUES ((select max(id) from public.food where name = 'Foks 0.33'), (select max(id) from public.category where name = 'Drinks'));
INSERT INTO public.food (name, photo, price, restaurant_id) VALUES ('Coca Cola 0.45', 'https://korpa.ba/product_uploads/u64fm8BDnz8q1mreoBUknfrZEJDf9nar.jpg', 80, (select max(id) from public.restaurant where name = 'Fat Kitchen Bistro'));
INSERT INTO public.category_of_food (food_id, category_id) VALUES ((select max(id) from public.food where name = 'Coca Cola 0.45'), (select max(id) from public.category where name = 'Drinks'));
INSERT INTO public.food (name, photo, price, restaurant_id) VALUES ('Coca Cola Zero 0.45', 'https://korpa.ba/product_uploads/nmBqygyg62pXjxkUnjaV8qyfA1tndXuF.jpg', 80, (select max(id) from public.restaurant where name = 'Fat Kitchen Bistro'));
INSERT INTO public.category_of_food (food_id, category_id) VALUES ((select max(id) from public.food where name = 'Coca Cola Zero 0.45'), (select max(id) from public.category where name = 'Drinks'));
INSERT INTO public.food (name, photo, price, restaurant_id) VALUES ('Next Lemonade 0.4', 'https://korpa.ba/product_uploads/st2h5YjpQumAMEDByBkDMj5eGCiVG9N3.jpg', 90, (select max(id) from public.restaurant where name = 'Fat Kitchen Bistro'));
INSERT INTO public.category_of_food (food_id, category_id) VALUES ((select max(id) from public.food where name = 'Next Lemonade 0.4'), (select max(id) from public.category where name = 'Drinks'));
INSERT INTO public.food (name, photo, price, restaurant_id) VALUES ('Скопско 0.5', 'https://korpa.ba/product_uploads/sxhmrlbOP9JP2EEW2adBRwX55h9y004V.jpg', 90, (select max(id) from public.restaurant where name = 'Fat Kitchen Bistro'));
INSERT INTO public.category_of_food (food_id, category_id) VALUES ((select max(id) from public.food where name = 'Скопско 0.5'), (select max(id) from public.category where name = 'Drinks'));
INSERT INTO public.food (name, photo, price, restaurant_id) VALUES ('Скопско Smooth 0.5', 'https://korpa.ba/product_uploads/XriuuUUd0uHPlCPKFgABu6bH1bhnQHaR.jpg', 90, (select max(id) from public.restaurant where name = 'Fat Kitchen Bistro'));
INSERT INTO public.category_of_food (food_id, category_id) VALUES ((select max(id) from public.food where name = 'Скопско Smooth 0.5'), (select max(id) from public.category where name = 'Drinks'));
INSERT INTO public.food (name, photo, price, restaurant_id) VALUES ('Heineken 0.5', 'https://korpa.ba/product_uploads/ejqLdQDPP9wKhw45bgyfVczi0K2GWGq5.jpg', 120, (select max(id) from public.restaurant where name = 'Fat Kitchen Bistro'));
INSERT INTO public.category_of_food (food_id, category_id) VALUES ((select max(id) from public.food where name = 'Heineken 0.5'), (select max(id) from public.category where name = 'Drinks'));
INSERT INTO public.food (name, photo, price, restaurant_id) VALUES ('Bira Morreti 0.5', 'https://korpa.ba/product_uploads/daTQKuSMuOfAAlorovsCLWVJMuDkeHOT.jpg', 140, (select max(id) from public.restaurant where name = 'Fat Kitchen Bistro'));
INSERT INTO public.category_of_food (food_id, category_id) VALUES ((select max(id) from public.food where name = 'Bira Morreti 0.5'), (select max(id) from public.category where name = 'Drinks'));
INSERT INTO public.food (name, photo, price, restaurant_id) VALUES ('Fanta 0.33', 'https://korpa.ba/product_uploads/gz9AmAATtZjpEjLivNbbevWYYyPlyOk0.png', 70, (select max(id) from public.restaurant where name = 'Fat Kitchen Bistro'));
INSERT INTO public.category_of_food (food_id, category_id) VALUES ((select max(id) from public.food where name = 'Fanta 0.33'), (select max(id) from public.category where name = 'Drinks'));
INSERT INTO public.food (name, photo, price, restaurant_id) VALUES ('100% природен сок од калинка', 'https://korpa.ba/product_uploads/TqFkXgbVzHii7ar9OjkOEu9Ff8s0B0Ha.jpg', 120, (select max(id) from public.restaurant where name = 'Fat Kitchen Bistro'));
INSERT INTO public.category_of_food (food_id, category_id) VALUES ((select max(id) from public.food where name = '100% природен сок од калинка'), (select max(id) from public.category where name = 'Drinks'));
INSERT INTO public.food (name, photo, price, restaurant_id) VALUES ('Blue Moon 0.33', 'https://korpa.ba/product_uploads/lQ6VrqulZGqoJScr8T4AiGMwRQU9djZj.jpg', 180, (select max(id) from public.restaurant where name = 'Fat Kitchen Bistro'));
INSERT INTO public.category_of_food (food_id, category_id) VALUES ((select max(id) from public.food where name = 'Blue Moon 0.33'), (select max(id) from public.category where name = 'Drinks'));